name: Deploy to IPFS

on:
  push:
    branches: [Master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install IPFS CLI
      run: |
        wget https://dist.ipfs.tech/go-ipfs/v0.18.1/go-ipfs_v0.18.1_linux-arm64.tar.gz
        tar -xvzf go-ipfs_v0.18.1_linux-arm64.tar.gz
        cd go-ipfs
        sudo bash install.sh

    - name: Add site to IPFS
      run: |
        ipfs init
        ipfs daemon &
        sleep 10
        ipfs add -r quiet-reference-site/ > ipfs_output.txt
        tail -n 1 ipfs_output.txt > cid.txt

    - name: Save CID as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ipfs-cid
        path: cid.txt
